/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const UploadLazyRouteImport = createFileRoute('/upload')()
const IndexLazyRouteImport = createFileRoute('/')()
const TraceFilesFileNameLazyRouteImport = createFileRoute(
  '/trace-files/$fileName',
)()
const TasksTaskIdLazyRouteImport = createFileRoute('/tasks/$taskId')()
const ReplayFileNameLazyRouteImport = createFileRoute('/replay/$fileName')()

const UploadLazyRoute = UploadLazyRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/upload.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TraceFilesFileNameLazyRoute = TraceFilesFileNameLazyRouteImport.update({
  id: '/trace-files/$fileName',
  path: '/trace-files/$fileName',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/trace-files/$fileName.lazy').then((d) => d.Route),
)
const TasksTaskIdLazyRoute = TasksTaskIdLazyRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tasks/$taskId.lazy').then((d) => d.Route))
const ReplayFileNameLazyRoute = ReplayFileNameLazyRouteImport.update({
  id: '/replay/$fileName',
  path: '/replay/$fileName',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/replay/$fileName.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/upload': typeof UploadLazyRoute
  '/replay/$fileName': typeof ReplayFileNameLazyRoute
  '/tasks/$taskId': typeof TasksTaskIdLazyRoute
  '/trace-files/$fileName': typeof TraceFilesFileNameLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/upload': typeof UploadLazyRoute
  '/replay/$fileName': typeof ReplayFileNameLazyRoute
  '/tasks/$taskId': typeof TasksTaskIdLazyRoute
  '/trace-files/$fileName': typeof TraceFilesFileNameLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/upload': typeof UploadLazyRoute
  '/replay/$fileName': typeof ReplayFileNameLazyRoute
  '/tasks/$taskId': typeof TasksTaskIdLazyRoute
  '/trace-files/$fileName': typeof TraceFilesFileNameLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upload'
    | '/replay/$fileName'
    | '/tasks/$taskId'
    | '/trace-files/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/replay/$fileName'
    | '/tasks/$taskId'
    | '/trace-files/$fileName'
  id:
    | '__root__'
    | '/'
    | '/upload'
    | '/replay/$fileName'
    | '/tasks/$taskId'
    | '/trace-files/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  UploadLazyRoute: typeof UploadLazyRoute
  ReplayFileNameLazyRoute: typeof ReplayFileNameLazyRoute
  TasksTaskIdLazyRoute: typeof TasksTaskIdLazyRoute
  TraceFilesFileNameLazyRoute: typeof TraceFilesFileNameLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-files/$fileName': {
      id: '/trace-files/$fileName'
      path: '/trace-files/$fileName'
      fullPath: '/trace-files/$fileName'
      preLoaderRoute: typeof TraceFilesFileNameLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/$fileName': {
      id: '/replay/$fileName'
      path: '/replay/$fileName'
      fullPath: '/replay/$fileName'
      preLoaderRoute: typeof ReplayFileNameLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  UploadLazyRoute: UploadLazyRoute,
  ReplayFileNameLazyRoute: ReplayFileNameLazyRoute,
  TasksTaskIdLazyRoute: TasksTaskIdLazyRoute,
  TraceFilesFileNameLazyRoute: TraceFilesFileNameLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
